### PR TITLE
fix(cypress-angular-dev-server): fixes error when using per project configuration files

### LINKED ISSUE #117: Error when using per project configuration files
**Description**

An error is thrown when using per project configuration files. That is, when each project has its own project.json. The error is "EISDIR: Illegal operation on a directory, read".

The error is coming from [this line](https://github.com/jscutlery/devkit/blob/main/packages/cypress-angular-dev-server/src/lib/find-target-options.ts#L56 ). It happens because it tries to read the directory instead of the project.json file, e.g. "libs/test" instead of "libs/test/project.json".

### PR DESCRIPTION
**Pull request by srleecode**
**Current Behavior**

When using per project configuration files an error is thrown and cypress cannot be started.

**Expected Behavior**

Cypress should be able to be started when using per project configuration files.

**Related Issue(s)**

Fixes #117

### CODE REVIEW

File: packages/cypress-angular-dev-server/src/lib/find-target-options.ts [hunk 1]
```diff
@@ -53,9 +53,12 @@ function _findOptions({
   /* Standalone project configuration case: */
   if (typeof workspaceDef?.projects?.[project] === 'string') {
     const standaloneDef = JSON.parse(
-      readFileSync(resolve(root, workspaceDef.projects[project]), {
-        encoding: 'utf-8',
-      })
+      readFileSync(
+        resolve(root, `${workspaceDef.projects[project]}/project.json`),
```
Comment (srleecode) [inline packages/cypress-angular-dev-server/src/lib/find-target-options.ts:57]: This is the only change to the code. The other updates are to add a test and to fix the tests that were failing. I am using windows which gives a different path "\\" instead of "/" and this was causing some of the tests to fail,

**Review by edbzn — APPROVED** [review]

File: packages/cypress-angular-dev-server/src/lib/find-target-options.ts (hunk 1 above)
Comment (edbzn) [reply packages/cypress-angular-dev-server/src/lib/find-target-options.ts:57]: Nice, thanks for the fix, appreciated!
